### ISSUE TITLE
11 errors on WIndows 10

### ISSUE THREAD

**Issue by 0joshuaolson1** [createuniverses/praxis#7]
Severity    Code    Description Project File    Line
Error   C2371   'uint32_t': redefinition; different basic types praxis  c:\users\joshua\desktop\praxis\io\Common.h  30
Error   C2371   'int32_t': redefinition; different basic types  praxis  c:\users\joshua\desktop\praxis\io\Common.h  31
Error   C3861   'max': identifier not found praxis  C:\Users\Joshua\Desktop\praxis\luaCBMidi.cpp    38
Error   C2664   'MMRESULT timeSetEvent(UINT,UINT,LPTIMECALLBACK,DWORD_PTR,UINT)': cannot convert argument 3 from 'void (__cdecl *)(UINT,UINT,DWORD,DWORD,DWORD)' to 'LPTIMECALLBACK'    praxis  C:\Users\Joshua\Desktop\praxis\luaCBMidi.cpp    39
Error   C2664   'MMRESULT timeSetEvent(UINT,UINT,LPTIMECALLBACK,DWORD_PTR,UINT)': cannot convert argument 3 from 'void (__cdecl *)(UINT,UINT,DWORD,DWORD,DWORD)' to 'LPTIMECALLBACK'    praxis  C:\Users\Joshua\Desktop\praxis\luaCBMidi.cpp    184
Error   C3861   'max': identifier not found praxis  C:\Users\Joshua\Desktop\praxis\luaCBMidi.cpp    200
Error   C2371   'uint32_t': redefinition; different basic types praxis  c:\users\joshua\desktop\praxis\io\PortableStdint.h  383
Error   C2371   'int32_t': redefinition; different basic types  praxis  c:\users\joshua\desktop\praxis\io\PortableStdint.h  413
Error   C2371   'int_fast16_t': redefinition; different basic types praxis  c:\users\joshua\desktop\praxis\io\PortableStdint.h  624
Error   C2371   'uint_fast16_t': redefinition; different basic types    praxis  c:\users\joshua\desktop\praxis\io\PortableStdint.h  625
Error   C1189   #error:  Macro definition of snprintf conflicts with Standard Library function declaration  praxis  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h    1927

**Comment by createuniverses** [comment]
Visual Studio 2010 Express is the compiler that is used for the Win32 build. In newer versions, VS might have got its act together and added definitions for uint32_t and the rest. Which version of Visual Studio are you using?

**Comment by MrMormon** [comment]
I used 2015

**Comment by createuniverses** [comment]
I suggest using VS2010 express to compile praxis. For the past 2 years, I've been using this with Qt 4.8.6. After reading your message, I tried building praxis with VS2012 with the qmake from Qt5.5 and it works, but ```GetSystemMetrics``` works differently, and that bothers me. The fix for it is a hack where I need to add 8 pixels to the output of ```GetSystemMetrics(SM_CXSIZEFRAME).``` I don't want to open a can of worms, fixing things that already work by switching, so I'm sticking with VS2010.

As for your compile error, I haven't seen that with either VS2010 or VS2012. Please note that the project file for praxis is for Qt Creator, not Visual Studio. VS2015 is not supported by the latest version of qmake (from Qt5.5), so if you're loading praxis into VS2015, you must be doing it manually.

FYI, here is a download link for VS2010 Express edition I use on the MS website someone posted to stackoverflow in June 2010:
http://download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso
http://stackoverflow.com/questions/3061811/how-to-get-download-link-to-vs2010-express-for-use-in-a-download-manager
